# Generated by Django 4.1.3 on 2022-12-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('Price', models.CharField(max_length=10)),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=10)),
                ('Quality', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('mediam', 'mediam')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='imagefolder')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], max_length=20)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmainmodel')),
            ],
        ),
    ]
